#!/bin/sh

usage(){
    echo "Usage: loginitems [-h | -a NAME [-p PATH] [-s HIDE?] | -d NAME | -l]"
    echo "  -h Show this help message."
    echo "  -a Add an application, optionally hide with -s false."
    echo "  -p Path to application; defaults to /Applications/NAME.app."
    echo "  -s Show/hide application; defaults to true (no hide)."
    echo "  -d Delete an application from login items."
    echo "  -l List all login items."
}

hide="false"
falsehood="false no 0"
opts="h:a:p:s:d:l"
while getopts "$opts" opt; do
    case "$opt" in
        a)
            action="add"
            name="${OPTARG}"
            if [ ! $path ]; then
                path="/Applications/$name.app"
            fi
            ;;
        p)
            path="${OPTARG}"
            ;;
        s)
            if [[ $falsehood =~ (^| )${OPTARG}($| ) ]]
                then  # false show, so do hide
                    hide="true"
            fi
            ;;
        d)
            action="delete"
            name="${OPTARG}"
            ;;
        l)
            action="list"
            ;;
        *)
            usage
            ;;
    esac
done

if [ "$action" = "add" ]; then
    loginitems-add "$name" "$path" $hide >> /dev/null
elif [ "$action" = "delete" ]; then
    loginitems-rm "$name" >> /dev/null
elif [ "$action" = "list" ]; then
    loginitems-ls
fi

